// Random, editable username suggestions: nothing derived from the email, so nothing leaks.
const ADJECTIVES = [
  "swift",
  "quiet",
  "brave",
  "lucky",
  "rapid",
  "sly",
  "bold",
  "calm",
  "clever",
  "fierce",
  "keen",
  "nimble",
  "sharp",
  "stormy",
  "sunny",
  "wild",
  "witty",
  "zesty",
  "bright",
  "cosmic",
  "frosty",
  "lunar",
  "mighty",
  "noble",
  "rusty",
  "silent",
  "spicy",
  "turbo",
  "vivid",
  "dizzy",
];
const NOUNS = [
  "otter",
  "falcon",
  "badger",
  "comet",
  "cobra",
  "fox",
  "lynx",
  "moth",
  "newt",
  "panda",
  "pixel",
  "raven",
  "rocket",
  "shark",
  "tiger",
  "viper",
  "wolf",
  "yak",
  "koala",
  "gecko",
  "heron",
  "bison",
  "orca",
  "mango",
  "pepper",
  "cactus",
  "byte",
  "loop",
  "stack",
  "parser",
];

const pick = (list) => list[Math.floor(Math.random() * list.length)];

// At most 6 + 1 + 6 + 1 + 2 = 16 characters, always valid under the username rules.
export function randomHandle() {
  return `${pick(ADJECTIVES)}-${pick(NOUNS)}-${10 + Math.floor(Math.random() * 90)}`;
}
